In [6]:
from ucimlrepo import fetch_ucirepo
import pandas as pd
  
# fetch dataset 
chronic_kidney_disease = fetch_ucirepo(id=336) 
  
# data (as pandas dataframes) 
X = chronic_kidney_disease.data.features 
y = chronic_kidney_disease.data.targets


df = pd.DataFrame(X)
df.head(20)

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,hemo,pcv,wbcc,rbcc,htn,dm,cad,appet,pe,ane
0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,...,15.4,44.0,7800.0,5.2,yes,yes,no,good,no,no
1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,...,11.3,38.0,6000.0,NaN,no,no,no,good,no,no
2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,...,9.6,31.0,7500.0,NaN,no,yes,no,poor,no,yes
3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,...,11.2,32.0,6700.0,3.9,yes,no,no,poor,yes,yes
4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,...,11.6,35.0,7300.0,4.6,no,no,no,good,no,no
5,60.0,90.0,1.015,3.0,0.0,NaN,NaN,notpresent,notpresent,74.0,...,12.2,39.0,7800.0,4.4,yes,yes,no,good,yes,no
6,68.0,70.0,1.010,0.0,0.0,NaN,normal,notpresent,notpresent,100.0,...,12.4,36.0,NaN,NaN,no,no,no,good,no,no
7,24.0,NaN,1.015,2.0,4.0,normal,abnormal,notpresent,notpresent,410.0,...,12.4,44.0,6900.0,5.0,no,yes,no,good,yes,no
8,52.0,100.0,1.015,3.0,0.0,normal,abnormal,present,notpresent,138.0,...,10.8,33.0,9600.0,4.0,yes,yes,no,good,no,yes
9,53.0,90.0,1.020,2.0,0.0,abnormal,abnormal,present,notpresent,70.0,...,9.5,29.0,12100.0,3.7,yes,yes,no,poor,no,yes
10,50.0,60.0,1.010,2.0,4.0,NaN,abnormal,present,notpresent,490.0,...,9.4,28.0,NaN,NaN,yes,yes,no,good,no,yes
11,63.0,70.0,1.010,3.0,0.0,abnormal,abnormal,present,notpresent,380.0,...,10.8,32.0,4500.0,3.8,yes,yes,no,poor,yes,no
12,68.0,70.0,1.015,3.0,1.0,NaN,normal,present,notpresent,208.0,...,9.7,28.0,12200.0,3.4,yes,yes,yes,poor,yes,no
13,68.0,70.0,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,98.0,...,9.8,NaN,NaN,NaN,yes,yes,yes,poor,yes,no
14,68.0,80.0,1.010,3.0,2.0,normal,abnormal,present,present,157.0,...,5.6,16.0,11000.0,2.6,yes,yes,yes,poor,yes,no
15,40.0,80.0,1.015,3.0,0.0,NaN,normal,notpresent,notpresent,76.0,...,7.6,24.0,3800.0,2.8,yes,no,no,good,no,yes
16,47.0,70.0,1.015,2.0,0.0,NaN,normal,notpresent,notpresent,99.0,...,12.6,NaN,NaN,NaN,no,no,no,good,no,no
17,47.0,80.0,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,114.0,...,12.1,NaN,NaN,NaN,yes,no,no,poor,no,no
18,60.0,100.0,1.025,0.0,3.0,NaN,normal,notpresent,notpresent,263.0,...,12.7,37.0,11400.0,4.3,yes,yes,yes,good,no,no
19,62.0,60.0,1.015,1.0,0.0,NaN,abnormal,present,notpresent,100.0,...,10.3,30.0,5300.0,3.7,yes,no,yes,good,no,no

In [14]:
df.pc.unique()

array(['normal', 'abnormal', nan], dtype=object)

In [17]:
df.dtypes

age       float64
bp        float64
sg        float64
al        float64
su        float64
rbc        object
pc         object
pcc      category
ba         object
bgr       float64
bu        float64
sc        float64
sod       float64
pot       float64
hemo      float64
pcv       float64
wbcc      float64
rbcc      float64
htn        object
dm         object
cad        object
appet      object
pe         object
ane        object
dtype: object

In [16]:
df['pcc'] = df['pcc'].astype('category')

In [18]:
df.head(20)

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,hemo,pcv,wbcc,rbcc,htn,dm,cad,appet,pe,ane
0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,...,15.4,44.0,7800.0,5.2,yes,yes,no,good,no,no
1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,...,11.3,38.0,6000.0,NaN,no,no,no,good,no,no
2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,...,9.6,31.0,7500.0,NaN,no,yes,no,poor,no,yes
3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,...,11.2,32.0,6700.0,3.9,yes,no,no,poor,yes,yes
4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,...,11.6,35.0,7300.0,4.6,no,no,no,good,no,no
5,60.0,90.0,1.015,3.0,0.0,NaN,NaN,notpresent,notpresent,74.0,...,12.2,39.0,7800.0,4.4,yes,yes,no,good,yes,no
6,68.0,70.0,1.010,0.0,0.0,NaN,normal,notpresent,notpresent,100.0,...,12.4,36.0,NaN,NaN,no,no,no,good,no,no
7,24.0,NaN,1.015,2.0,4.0,normal,abnormal,notpresent,notpresent,410.0,...,12.4,44.0,6900.0,5.0,no,yes,no,good,yes,no
8,52.0,100.0,1.015,3.0,0.0,normal,abnormal,present,notpresent,138.0,...,10.8,33.0,9600.0,4.0,yes,yes,no,good,no,yes
9,53.0,90.0,1.020,2.0,0.0,abnormal,abnormal,present,notpresent,70.0,...,9.5,29.0,12100.0,3.7,yes,yes,no,poor,no,yes
10,50.0,60.0,1.010,2.0,4.0,NaN,abnormal,present,notpresent,490.0,...,9.4,28.0,NaN,NaN,yes,yes,no,good,no,yes
11,63.0,70.0,1.010,3.0,0.0,abnormal,abnormal,present,notpresent,380.0,...,10.8,32.0,4500.0,3.8,yes,yes,no,poor,yes,no
12,68.0,70.0,1.015,3.0,1.0,NaN,normal,present,notpresent,208.0,...,9.7,28.0,12200.0,3.4,yes,yes,yes,poor,yes,no
13,68.0,70.0,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,98.0,...,9.8,NaN,NaN,NaN,yes,yes,yes,poor,yes,no
14,68.0,80.0,1.010,3.0,2.0,normal,abnormal,present,present,157.0,...,5.6,16.0,11000.0,2.6,yes,yes,yes,poor,yes,no
15,40.0,80.0,1.015,3.0,0.0,NaN,normal,notpresent,notpresent,76.0,...,7.6,24.0,3800.0,2.8,yes,no,no,good,no,yes
16,47.0,70.0,1.015,2.0,0.0,NaN,normal,notpresent,notpresent,99.0,...,12.6,NaN,NaN,NaN,no,no,no,good,no,no
17,47.0,80.0,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,114.0,...,12.1,NaN,NaN,NaN,yes,no,no,poor,no,no
18,60.0,100.0,1.025,0.0,3.0,NaN,normal,notpresent,notpresent,263.0,...,12.7,37.0,11400.0,4.3,yes,yes,yes,good,no,no
19,62.0,60.0,1.015,1.0,0.0,NaN,abnormal,present,notpresent,100.0,...,10.3,30.0,5300.0,3.7,yes,no,yes,good,no,no

In [19]:
df.pcc.unique()

['notpresent', 'present', NaN]
Categories (2, object): ['notpresent', 'present']

In [20]:
df['pc'] = df['pc'].astype('category')

In [21]:
df.pc.unique()

['normal', 'abnormal', NaN]
Categories (2, object): ['abnormal', 'normal']

In [22]:
df.head(20)

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,hemo,pcv,wbcc,rbcc,htn,dm,cad,appet,pe,ane
0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,...,15.4,44.0,7800.0,5.2,yes,yes,no,good,no,no
1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,...,11.3,38.0,6000.0,NaN,no,no,no,good,no,no
2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,...,9.6,31.0,7500.0,NaN,no,yes,no,poor,no,yes
3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,...,11.2,32.0,6700.0,3.9,yes,no,no,poor,yes,yes
4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,...,11.6,35.0,7300.0,4.6,no,no,no,good,no,no
5,60.0,90.0,1.015,3.0,0.0,NaN,NaN,notpresent,notpresent,74.0,...,12.2,39.0,7800.0,4.4,yes,yes,no,good,yes,no
6,68.0,70.0,1.010,0.0,0.0,NaN,normal,notpresent,notpresent,100.0,...,12.4,36.0,NaN,NaN,no,no,no,good,no,no
7,24.0,NaN,1.015,2.0,4.0,normal,abnormal,notpresent,notpresent,410.0,...,12.4,44.0,6900.0,5.0,no,yes,no,good,yes,no
8,52.0,100.0,1.015,3.0,0.0,normal,abnormal,present,notpresent,138.0,...,10.8,33.0,9600.0,4.0,yes,yes,no,good,no,yes
9,53.0,90.0,1.020,2.0,0.0,abnormal,abnormal,present,notpresent,70.0,...,9.5,29.0,12100.0,3.7,yes,yes,no,poor,no,yes
10,50.0,60.0,1.010,2.0,4.0,NaN,abnormal,present,notpresent,490.0,...,9.4,28.0,NaN,NaN,yes,yes,no,good,no,yes
11,63.0,70.0,1.010,3.0,0.0,abnormal,abnormal,present,notpresent,380.0,...,10.8,32.0,4500.0,3.8,yes,yes,no,poor,yes,no
12,68.0,70.0,1.015,3.0,1.0,NaN,normal,present,notpresent,208.0,...,9.7,28.0,12200.0,3.4,yes,yes,yes,poor,yes,no
13,68.0,70.0,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,98.0,...,9.8,NaN,NaN,NaN,yes,yes,yes,poor,yes,no
14,68.0,80.0,1.010,3.0,2.0,normal,abnormal,present,present,157.0,...,5.6,16.0,11000.0,2.6,yes,yes,yes,poor,yes,no
15,40.0,80.0,1.015,3.0,0.0,NaN,normal,notpresent,notpresent,76.0,...,7.6,24.0,3800.0,2.8,yes,no,no,good,no,yes
16,47.0,70.0,1.015,2.0,0.0,NaN,normal,notpresent,notpresent,99.0,...,12.6,NaN,NaN,NaN,no,no,no,good,no,no
17,47.0,80.0,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,114.0,...,12.1,NaN,NaN,NaN,yes,no,no,poor,no,no
18,60.0,100.0,1.025,0.0,3.0,NaN,normal,notpresent,notpresent,263.0,...,12.7,37.0,11400.0,4.3,yes,yes,yes,good,no,no
19,62.0,60.0,1.015,1.0,0.0,NaN,abnormal,present,notpresent,100.0,...,10.3,30.0,5300.0,3.7,yes,no,yes,good,no,no

In [23]:
df.ba.unique()

array(['notpresent', 'present', nan], dtype=object)

In [24]:
df['ba'] = df['ba'].astype('category')

In [25]:
df.ba.unique()

['notpresent', 'present', NaN]
Categories (2, object): ['notpresent', 'present']

In [27]:
df.rbc.unique()

array([nan, 'normal', 'abnormal'], dtype=object)

In [28]:
df['rbc'] = df['rbc'].astype('category')

In [29]:
df.dtypes

age       float64
bp        float64
sg        float64
al        float64
su        float64
rbc      category
pc       category
pcc      category
ba       category
bgr       float64
bu        float64
sc        float64
sod       float64
pot       float64
hemo      float64
pcv       float64
wbcc      float64
rbcc      float64
htn        object
dm         object
cad        object
appet      object
pe         object
ane        object
dtype: object

In [31]:
df.describe(include='all')

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,hemo,pcv,wbcc,rbcc,htn,dm,cad,appet,pe,ane
count,391.000000,388.000000,353.000000,354.000000,351.000000,248,335,396,396,356.000000,...,348.000000,329.000000,294.000000,269.000000,398,398,398,399,399,399
unique,NaN,NaN,NaN,NaN,NaN,2,2,2,2,NaN,...,NaN,NaN,NaN,NaN,2,3,2,2,2,2
top,NaN,NaN,NaN,NaN,NaN,normal,normal,notpresent,notpresent,NaN,...,NaN,NaN,NaN,NaN,no,no,no,good,no,no
freq,NaN,NaN,NaN,NaN,NaN,201,259,354,374,NaN,...,NaN,NaN,NaN,NaN,251,260,364,317,323,339
mean,51.483376,76.469072,1.017408,1.016949,0.450142,NaN,NaN,NaN,NaN,148.036517,...,12.526437,38.884498,8406.122449,4.707435,NaN,NaN,NaN,NaN,NaN,NaN
std,17.169714,13.683637,0.005717,1.352679,1.099191,NaN,NaN,NaN,NaN,79.281714,...,2.912587,8.990105,2944.474190,1.025323,NaN,NaN,NaN,NaN,NaN,NaN
min,2.000000,50.000000,1.005000,0.000000,0.000000,NaN,NaN,NaN,NaN,22.000000,...,3.100000,9.000000,2200.000000,2.100000,NaN,NaN,NaN,NaN,NaN,NaN
25%,42.000000,70.000000,1.010000,0.000000,0.000000,NaN,NaN,NaN,NaN,99.000000,...,10.300000,32.000000,6500.000000,3.900000,NaN,NaN,NaN,NaN,NaN,NaN
50%,55.000000,80.000000,1.020000,0.000000,0.000000,NaN,NaN,NaN,NaN,121.000000,...,12.650000,40.000000,8000.000000,4.800000,NaN,NaN,NaN,NaN,NaN,NaN
75%,64.500000,80.000000,1.020000,2.000000,0.000000,NaN,NaN,NaN,NaN,163.000000,...,15.000000,45.000000,9800.000000,5.400000,NaN,NaN,NaN,NaN,NaN,NaN
max,90.000000,180.000000,1.025000,5.000000,5.000000,NaN,NaN,NaN,NaN,490.000000,...,17.800000,54.000000,26400.000000,8.000000,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
rename_mapping = {
    'bp': 'blood pressure',
    'sg': 'specific gravity',
    'al': 'albumin',
    'su': 'sugar',
    'bgr': 'blood glucose random',
    'bu': 'blood urea',
    'sod': 'sodium',
    'pot': 'potassium',
    'hemo': 'hemoglobin',
    'pcv': 'packed cell volume',
    'wbcc': 'white blood cell count',
    'rbcc': 'red blood cell count'
}

In [33]:
columns_to_drop = ['pc', 'pcc', 'ba', 'sc', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane']

In [34]:
df = df.rename(columns=rename_mapping)
df = df.drop(columns=columns_to_drop,
             errors='ignore')

In [35]:
print(df.columns)

Index(['age', 'blood pressure', 'specific gravity', 'albumin', 'sugar', 'rbc',
       'blood glucose random', 'blood urea', 'sodium', 'potassium',
       'hemoglobin', 'packed cell volume', 'white blood cell count',
       'red blood cell count'],
      dtype='object')

In [36]:
df = df.rename(columns={'rbc': 'red blood cell count'})

In [37]:
print(df.columns)

Index(['age', 'blood pressure', 'specific gravity', 'albumin', 'sugar',
       'red blood cell count', 'blood glucose random', 'blood urea', 'sodium',
       'potassium', 'hemoglobin', 'packed cell volume',
       'white blood cell count', 'red blood cell count'],
      dtype='object')

In [38]:
df.dtypes

age                        float64
blood pressure             float64
specific gravity           float64
albumin                    float64
sugar                      float64
red blood cell count      category
blood glucose random       float64
blood urea                 float64
sodium                     float64
potassium                  float64
hemoglobin                 float64
packed cell volume         float64
white blood cell count     float64
red blood cell count       float64
dtype: object

In [43]:
df['hemoglobin'] = df['hemoglobin'] * 10 # Converts to g/l

In [41]:
df.head(20)

,age,blood pressure,specific gravity,albumin,sugar,red blood cell count,blood glucose random,blood urea,sodium,potassium,hemoglobin,packed cell volume,white blood cell count,red blood cell count
0,48.0,80.0,1.020,1.0,0.0,NaN,121.0,36.0,NaN,NaN,1540.0,44.0,7800.0,5.2
1,7.0,50.0,1.020,4.0,0.0,NaN,NaN,18.0,NaN,NaN,1130.0,38.0,6000.0,NaN
2,62.0,80.0,1.010,2.0,3.0,normal,423.0,53.0,NaN,NaN,960.0,31.0,7500.0,NaN
3,48.0,70.0,1.005,4.0,0.0,normal,117.0,56.0,111.0,2.5,1120.0,32.0,6700.0,3.9
4,51.0,80.0,1.010,2.0,0.0,normal,106.0,26.0,NaN,NaN,1160.0,35.0,7300.0,4.6
5,60.0,90.0,1.015,3.0,0.0,NaN,74.0,25.0,142.0,3.2,1220.0,39.0,7800.0,4.4
6,68.0,70.0,1.010,0.0,0.0,NaN,100.0,54.0,104.0,4.0,1240.0,36.0,NaN,NaN
7,24.0,NaN,1.015,2.0,4.0,normal,410.0,31.0,NaN,NaN,1240.0,44.0,6900.0,5.0
8,52.0,100.0,1.015,3.0,0.0,normal,138.0,60.0,NaN,NaN,1080.0,33.0,9600.0,4.0
9,53.0,90.0,1.020,2.0,0.0,abnormal,70.0,107.0,114.0,3.7,950.0,29.0,12100.0,3.7
10,50.0,60.0,1.010,2.0,4.0,NaN,490.0,55.0,NaN,NaN,940.0,28.0,NaN,NaN
11,63.0,70.0,1.010,3.0,0.0,abnormal,380.0,60.0,131.0,4.2,1080.0,32.0,4500.0,3.8
12,68.0,70.0,1.015,3.0,1.0,NaN,208.0,72.0,138.0,5.8,970.0,28.0,12200.0,3.4
13,68.0,70.0,NaN,NaN,NaN,NaN,98.0,86.0,135.0,3.4,980.0,NaN,NaN,NaN
14,68.0,80.0,1.010,3.0,2.0,normal,157.0,90.0,130.0,6.4,560.0,16.0,11000.0,2.6
15,40.0,80.0,1.015,3.0,0.0,NaN,76.0,162.0,141.0,4.9,760.0,24.0,3800.0,2.8
16,47.0,70.0,1.015,2.0,0.0,NaN,99.0,46.0,138.0,4.1,1260.0,NaN,NaN,NaN
17,47.0,80.0,NaN,NaN,NaN,NaN,114.0,87.0,139.0,3.7,1210.0,NaN,NaN,NaN
18,60.0,100.0,1.025,0.0,3.0,NaN,263.0,27.0,135.0,4.3,1270.0,37.0,11400.0,4.3
19,62.0,60.0,1.015,1.0,0.0,NaN,100.0,31.0,NaN,NaN,1030.0,30.0,5300.0,3.7

In [46]:
df.describe(include='all')

,age,blood pressure,specific gravity,albumin,sugar,red blood cell count,blood glucose random,blood urea,sodium,potassium,hemoglobin,packed cell volume,white blood cell count,red blood cell count
count,391.000000,388.000000,353.000000,354.000000,351.000000,248,356.000000,381.000000,313.000000,312.000000,348.000000,329.000000,294.000000,269.000000
unique,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,51.483376,76.469072,1.017408,1.016949,0.450142,NaN,148.036517,57.425722,137.528754,4.627244,125.264368,38.884498,8406.122449,4.707435
std,17.169714,13.683637,0.005717,1.352679,1.099191,NaN,79.281714,50.503006,10.408752,3.193904,29.125866,8.990105,2944.474190,1.025323
min,2.000000,50.000000,1.005000,0.000000,0.000000,NaN,22.000000,1.500000,4.500000,2.500000,31.000000,9.000000,2200.000000,2.100000
25%,42.000000,70.000000,1.010000,0.000000,0.000000,NaN,99.000000,27.000000,135.000000,3.800000,103.000000,32.000000,6500.000000,3.900000
50%,55.000000,80.000000,1.020000,0.000000,0.000000,NaN,121.000000,42.000000,138.000000,4.400000,126.500000,40.000000,8000.000000,4.800000
75%,64.500000,80.000000,1.020000,2.000000,0.000000,NaN,163.000000,66.000000,142.000000,4.900000,150.000000,45.000000,9800.000000,5.400000
max,90.000000,180.000000,1.025000,5.000000,5.000000,NaN,490.000000,391.000000,163.000000,47.000000,178.000000,54.000000,26400.000000,8.000000

In [47]:
df.dtypes

age                        float64
blood pressure             float64
specific gravity           float64
albumin                    float64
sugar                      float64
red blood cell count      category
blood glucose random       float64
blood urea                 float64
sodium                     float64
potassium                  float64
hemoglobin                 float64
packed cell volume         float64
white blood cell count     float64
red blood cell count       float64
dtype: object

In [50]:
print(chronic_kidney_disease.variables)

     name     role         type demographic              description  \
0     age  Feature      Integer         Age                     None
1      bp  Feature      Integer        None           blood pressure
2      sg  Feature  Categorical        None         specific gravity
3      al  Feature  Categorical        None                  albumin
4      su  Feature  Categorical        None                    sugar
5     rbc  Feature       Binary        None          red blood cells
6      pc  Feature       Binary        None                 pus cell
7     pcc  Feature       Binary        None          pus cell clumps
8      ba  Feature       Binary        None                 bacteria
9     bgr  Feature      Integer        None     blood glucose random
10     bu  Feature      Integer        None               blood urea
11     sc  Feature   Continuous        None         serum creatinine
12    sod  Feature      Integer        None                   sodium
13    pot  Feature   Continuous        None                potassium
14   hemo  Feature   Continuous        None               hemoglobin
15    pcv  Feature      Integer        None       packed cell volume
16   wbcc  Feature      Integer        None   white blood cell count
17   rbcc  Feature   Continuous        None     red blood cell count
18    htn  Feature       Binary        None             hypertension
19     dm  Feature       Binary        None        diabetes mellitus
20    cad  Feature       Binary        None  coronary artery disease
21  appet  Feature       Binary        None                 appetite
22     pe  Feature       Binary        None              pedal edema
23    ane  Feature       Binary        None                   anemia
24  class   Target       Binary        None           ckd or not ckd

           units missing_values
0           year            yes
1          mm/Hg            yes
2           None            yes
3           None            yes
4           None            yes
5           None            yes
6           None            yes
7           None            yes
8           None            yes
9         mgs/dl            yes
10        mgs/dl            yes
11        mgs/dl            yes
12         mEq/L            yes
13         mEq/L            yes
14           gms            yes
15          None            yes
16     cells/cmm            yes
17  millions/cmm            yes
18          None            yes
19          None            yes
20          None            yes
21          None            yes
22          None            yes
23          None            yes
24          None             no

In [52]:
df['class'] = y

In [54]:
df.head(20)

,age,blood pressure,specific gravity,albumin,sugar,red blood cell count,blood glucose random,blood urea,sodium,potassium,hemoglobin,packed cell volume,white blood cell count,red blood cell count,class
0,48.0,80.0,1.020,1.0,0.0,NaN,121.0,36.0,NaN,NaN,154.0,44.0,7800.0,5.2,ckd
1,7.0,50.0,1.020,4.0,0.0,NaN,NaN,18.0,NaN,NaN,113.0,38.0,6000.0,NaN,ckd
2,62.0,80.0,1.010,2.0,3.0,normal,423.0,53.0,NaN,NaN,96.0,31.0,7500.0,NaN,ckd
3,48.0,70.0,1.005,4.0,0.0,normal,117.0,56.0,111.0,2.5,112.0,32.0,6700.0,3.9,ckd
4,51.0,80.0,1.010,2.0,0.0,normal,106.0,26.0,NaN,NaN,116.0,35.0,7300.0,4.6,ckd
5,60.0,90.0,1.015,3.0,0.0,NaN,74.0,25.0,142.0,3.2,122.0,39.0,7800.0,4.4,ckd
6,68.0,70.0,1.010,0.0,0.0,NaN,100.0,54.0,104.0,4.0,124.0,36.0,NaN,NaN,ckd
7,24.0,NaN,1.015,2.0,4.0,normal,410.0,31.0,NaN,NaN,124.0,44.0,6900.0,5.0,ckd
8,52.0,100.0,1.015,3.0,0.0,normal,138.0,60.0,NaN,NaN,108.0,33.0,9600.0,4.0,ckd
9,53.0,90.0,1.020,2.0,0.0,abnormal,70.0,107.0,114.0,3.7,95.0,29.0,12100.0,3.7,ckd
10,50.0,60.0,1.010,2.0,4.0,NaN,490.0,55.0,NaN,NaN,94.0,28.0,NaN,NaN,ckd
11,63.0,70.0,1.010,3.0,0.0,abnormal,380.0,60.0,131.0,4.2,108.0,32.0,4500.0,3.8,ckd
12,68.0,70.0,1.015,3.0,1.0,NaN,208.0,72.0,138.0,5.8,97.0,28.0,12200.0,3.4,ckd
13,68.0,70.0,NaN,NaN,NaN,NaN,98.0,86.0,135.0,3.4,98.0,NaN,NaN,NaN,ckd
14,68.0,80.0,1.010,3.0,2.0,normal,157.0,90.0,130.0,6.4,56.0,16.0,11000.0,2.6,ckd
15,40.0,80.0,1.015,3.0,0.0,NaN,76.0,162.0,141.0,4.9,76.0,24.0,3800.0,2.8,ckd
16,47.0,70.0,1.015,2.0,0.0,NaN,99.0,46.0,138.0,4.1,126.0,NaN,NaN,NaN,ckd
17,47.0,80.0,NaN,NaN,NaN,NaN,114.0,87.0,139.0,3.7,121.0,NaN,NaN,NaN,ckd
18,60.0,100.0,1.025,0.0,3.0,NaN,263.0,27.0,135.0,4.3,127.0,37.0,11400.0,4.3,ckd
19,62.0,60.0,1.015,1.0,0.0,NaN,100.0,31.0,NaN,NaN,103.0,30.0,5300.0,3.7,ckd

In [55]:
df.dtypes

age                        float64
blood pressure             float64
specific gravity           float64
albumin                    float64
sugar                      float64
red blood cell count      category
blood glucose random       float64
blood urea                 float64
sodium                     float64
potassium                  float64
hemoglobin                 float64
packed cell volume         float64
white blood cell count     float64
red blood cell count       float64
class                       object
dtype: object

In [56]:
print(df['class'].unique())

['ckd' 'ckd\t' 'notckd']